---
title: "Themed dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: minty
      heading_font:
        google: Sen
      base_font: 
        google: Prompt
    orientation: rows
    self_contained: false
    vertical_layout: scroll
    source_code: embed
    navbar:
      - { title: "Github", href: "https://github.com/shrish-shete20/weblate", align: right, icon: fa-github}
    css: ["fragments/custom.css"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(htmltools)
library(fontawesome)
library(reactable)
source("Data_contains.R")
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
#thematic::thematic_rmd()
```


Sidebar {.sidebar data-width=200}
=====================================
```{r, echo=FALSE, results='asis'}
htmltools::includeHTML('fragments/sidebar.html')
```

Leaderboard
=====================================

Row {data-height=450}
-----------------------------------------------------------------------

### Weblate Leaderboard

```{r}
Statistics$Languages <- lapply(Statistics$Languages, function(x) {
  if (startsWith(x, "c(")) {
    eval(parse(text = x))
  } else {
    x
  }
})
board<-Statistics[order(Statistics$translated,decreasing = TRUE),]
boards<-board %>% select(name,username,translated,Languages,Active)

```


world-map
=====================================

Row {data-height=450}
-----------------------------------------------------------------------

hello