---
title: "Untitled"
output: html_document
date: "2023-07-13"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(htmltools)
library(fontawesome)
library(reactable)
library(dplyr)
library(crosstalk)
library(DT)
library(plotly)
library(reshape2)
library(formattable)
library(htmlwidgets)
source("Data_contains.R")
```

```{r echo=FALSE}
library(plotly)
lib<-unique(Library_Language_Statistics$Library)
# Your code for creating the initial plot
fig <- plot_ly(Library_Language_Statistics, x = ~Language, y = ~Translated, text = ~Language, type = 'scatter', mode = 'markers', size = ~Translated, color = ~Language, colors = 'Paired',
               marker = list(opacity = 0.5, sizemode = 'diameter'))
fig <- fig %>% layout(title = 'Gender Gap in Earnings per University',
                      xaxis = list(showgrid = FALSE),
                      yaxis = list(showgrid = FALSE),
                      showlegend = TRUE)

# Create a list of buttons for the dropdown menu
buttons <- lapply(1:length(lib), function(i) {
  list(
    method = "restyle",
    args = list("transforms[0].value", lib[i]),
    label = lib[i],
    args2 = list(list(title = lib[i]))
  )
})

# Create a JavaScript function to handle button click event
js <- '
function handleClick(index) {
  var chosenLibrary = index;
  console.log(chosenLibrary);
  var plotDiv = document.getElementById("myPlot");
  
  // Update the plot data based on the chosen library
  Plotly.restyle(plotDiv, {
    x: [Library_Language_Statistics[index].Language],
    y: [Library_Language_Statistics[index].Translated],
    text: [Library_Language_Statistics[index].Language],
    marker: {
      size: [Library_Language_Statistics[index].Translated],
      color: [Library_Language_Statistics[index].Language]
    }
  });
  
  // Update the plot title
  Plotly.relayout(plotDiv, {
    title: "Gender Gap in Earnings per University - " + Library_Language_Statistics[index].Library
  });
}'

# Add the JavaScript code to the plot
fig <- fig %>% onRender(js)

# Add the dropdown menu to the plot
fig <- fig %>% layout(
  updatemenus = list(
    list(
      y = 0.8,
      buttons = buttons
    )
  )
)


```


```{r echo=TRUE}
fig
```