name: Dashboard Refresh

on: 
  schedule:  
    - cron:  '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  Running_R_scripts:
    runs-on: ubuntu-20.04  
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
    - name: Install Packages
      run: |
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e 'install.packages("data.table")'
        Rscript -e 'install.packages("utils")'
        Rscript -e 'install.packages("stringr")'
        Rscript -e 'install.packages("readr")'
        Rscript -e 'install.packages("rvest")'
        
        
        
    - name: Run R scripts
      run: | 
        Rscript "Language Statisitics/Languages_Statistics.R"
        Rscript "Library Language Statistics/Library Language Statistics.R"
        Rscript "Recent Changes/Recent changes.R"
        Rscript "User Statistics/User_statistics.R"
      
    - name: Configure 
      run: |
        git config --global user.name "shrish-shete20"
        git config --global user.email "sheteshrish1203@gmail.com"
    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Updated Csv"
        git push
