name: Slack refresh

on: 
  schedule:  
    - cron:  '40 12 * * *'
  push:
    branches:
      - main
jobs:
  Running_R_scripts:
    runs-on: ubuntu-20.04 
    defaults:
      run:
        working-directory: Slack
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Print working directory
      run: pwd
    - uses: r-lib/actions/setup-r-dependencies@v2
    - name: Install Packages
      run: |
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e 'install.packages("slackr")'
        Rscript -e 'install.packages("stringr")'
        Rscript -e 'install.packages("readr")'
    - name: Run R scripts
      run: | 
        Rscript "Weblate_Slack.R"
      
    - name: Configure 
      run: |
        git config --global user.name "shrish-shete20"
        git config --global user.email "sheteshrish1203@gmail.com"
