name: User refresh

on: 
  schedule:  
    - cron:  '30 12 * * *'
  push:
    branches:
      - main
jobs:
  Running_R_scripts:
    runs-on: ubuntu-20.04 
    defaults:
      run:
        working-directory: User Statistics
    steps:
    - name: checkout_repo
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2
    - name: Print working directory
      run: pwd
    - uses: r-lib/actions/setup-r-dependencies@v2
    - name: Install Packages
      run: |
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e 'install.packages("data.table")'
        Rscript -e 'install.packages("rvest")'
        Rscript -e 'install.packages("readr")'   
        Rscript -e 'install.packages("dplyr")'
        Rscript -e 'install.packages("lubridate")'   
    - name: Run R scripts
      run: | 
        Rscript "User_statistics.R"
      
    - name: Configure 
      run: |
        git config --global user.name "shrish-shete20"
        git config --global user.email "sheteshrish1203@gmail.com"
    - name: Commit and Push Changes
      run: |
        git pull origin main
        git add .
        git commit -m "Updated users Csv"
        git push
